### ISSUE TITLE
React example music player does not work

### ISSUE THREAD

**Issue by trung2012** [Napster/napster.js#24]
Hello,

I cloned the react example and ran npm start. The app opened but the music player does not play any song. This was working a week ago.

Attached is the error in console. 

![image](https://user-images.githubusercontent.com/5129617/63983803-f4563280-ca8d-11e9-832d-1e8d84b3d25e.png)

**Comment by Filtos** [comment]
Hello @trung2012,
I've been trying to replicate the issue but no luck. Are you still able to hit this error?

**Comment by trung2012** [comment]
Hi @Filtos ,
Yes, I am still getting this error.

In fact I'm also getting another error 

![image](https://user-images.githubusercontent.com/5129617/64887381-12936500-d62e-11e9-8b3e-61ef4e4a6a57.png)

**Comment by Filtos** [comment]
Trying to make sure we are starting on the same page. Have you tried pulling down the code recently? We have made some changes in the last couple of days.
Also, the first issue could be due to an expired access token. When you launch the app make sure it takes you through the auth flow to get an updated access token.

**Comment by trung2012** [comment]
Hi @Filtos,

Yes I tried to clone it again today. I replaced the API_KEY and API_SECRET with mine and when running npm start it did redirect to the auth page. I clicked on Authorize and it took me to the main page. Then when I tried to play something it just logged out that error. The ?code value was a new one so I believe I got a new token.

**Comment by Filtos** [comment]
Looks like the issue was on our side. There was a bug that would revoke access from apps when trying to generate a new key and secret. We are working on a fix right now.
To fix your problem we have given your app the appropriate rights. Let us know if this fixed it (make sure to get another access token upon app launch).

**Comment by trung2012** [comment]
Hi @Filtos,

I tried again but it still gave me the same error. Could you please check again?

**Comment by Filtos** [comment]
Does the account that you are authorizing with have an active subscription? Currently we give developer accounts a temporary subscription, so that might have expired for you. I was able to get the same error as you when I tested with an account without an active subscription. Let me know if that is the case for you.

**Comment by trung2012** [comment]
Oh I guess that's why. The account I'm using does not have an active subscription.

**Comment by trung2012** [comment]
Clarified

**Comment by ChrisHeiden** [comment]
Hey,

I guess I have the same mistake. I also do not have an active subscription. Is is possible that you give me a temporary subscription again?

Here is the error message I have:
![image](https://user-images.githubusercontent.com/18535694/78119859-5a7eab80-7409-11ea-966b-4ec901cd226a.png)
